"""Reconstruct two printable zcar parts and evaluate a provisional battery box.

Inputs must pass inspect_zcar.py. No source mesh repair or editing is performed.
Generated STL parts are upstream-derived; retain the upstream GPL-3.0 license.
"""

import argparse
import json
from pathlib import Path
import shutil

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
import numpy as np
import trimesh

from inspect_zcar import inspect


def unique_part(parts, extents):
    matches = [(i, p) for i, p in enumerate(parts)
               if np.allclose(p.extents, extents, atol=0.01)]
    if len(matches) != 1:
        raise ValueError(f"Ambiguous component extents: {extents}")
    return matches[0]


def box(extents, center):
    result = trimesh.creation.box(extents=extents)
    result.apply_translation(center)
    return result


def overlap(a, b):
    result = trimesh.boolean.intersection([a, b], engine="manifold")
    return 0.0 if result.is_empty else float(result.volume)


def broad_phase(parts, bounds, excluded):
    return [i for i, p in enumerate(parts) if i not in excluded
            and np.all(p.bounds[1] > bounds[0])
            and np.all(p.bounds[0] < bounds[1])]


def aligned_part(source, target, rotation):
    result = source.copy()
    transform = np.eye(4)
    transform[:3, :3] = rotation
    result.apply_transform(transform)
    result.apply_translation(target.bounds.mean(axis=0) - result.bounds.mean(axis=0))
    # Assembly meshes have missing faces. Compare to surfaces, retain outliers,
    # and require 95% of vertices to agree rather than hiding those differences.
    distances = np.concatenate([
        trimesh.proximity.closest_point_naive(target, batch)[1]
        for batch in np.array_split(result.vertices, 20) if len(batch)
    ])
    if np.percentile(distances, 95) > 0.001:
        raise ValueError("Printable part does not align with the assembly")
    return result, {
        "max_distance_mm": float(distances.max()),
        "p95_distance_mm": float(np.percentile(distances, 95)),
        "vertices_farther_than_0_001mm": int(np.count_nonzero(distances > 0.001)),
    }


def main(root, output):
    provenance = inspect(root)
    trays = trimesh.load_mesh(root / "stl/tray1.stl").split(
        only_watertight=False, repair=False)
    assembly = trimesh.load_mesh(root / "stl/zcar.stl").split(
        only_watertight=False, repair=False)
    frame_i, frame_target = unique_part(assembly, [49.5, 117.375, 23.25])
    cover_i, cover_target = unique_part(assembly, [49.5, 47.05, 19])
    _, frame_source = unique_part(trays, [49.5, 117.375, 23.25])
    _, cover_source = unique_part(trays, [19, 47.05, 49.5])
    frame, frame_error = aligned_part(frame_source, frame_target, np.eye(3))
    cover, cover_error = aligned_part(
        cover_source, cover_target, np.array([[0, 0, -1], [0, 1, 0], [1, 0, 0]]))
    origin = frame_target.bounds[0].copy()
    for mesh in [frame, cover, *assembly]:
        mesh.apply_translation(-origin)
    if not frame.is_volume or not cover.is_volume:
        raise ValueError("Boolean checks require valid closed oriented volumes")

    battery = box([49, 18, 15], [24.75, 55, 10.25])
    # Union of every intermediate position in a 50 mm straight lateral slide.
    swept = box([99, 18, 15], [-0.25, 55, 10.25])
    lifted = battery.copy()
    lifted.apply_translation([0, 0, 1])
    measurements = {}
    for label, candidate in [("installed", battery), ("lateral_sweep", swept),
                             ("lifted_1mm", lifted)]:
        measurements[label] = {
            "bounds_mm": candidate.bounds.tolist(),
            "frame_intersection_mm3": overlap(candidate, frame),
            "cover_intersection_mm3": overlap(candidate, cover),
            "other_assembly_aabb_overlaps": broad_phase(
                assembly, candidate.bounds, {frame_i, cover_i}),
        }
    if measurements["lifted_1mm"]["cover_intersection_mm3"] <= 0:
        raise ValueError("Positive collision control failed")

    output.mkdir(parents=True, exist_ok=True)
    for name, mesh in [("frame", frame), ("cover", cover), ("battery", battery)]:
        mesh.export(output / f"{name}.stl")
    shutil.copyfile(root / "LICENSE", output / "UPSTREAM-LICENSE")
    (output / "SOURCE.txt").write_text(
        f"frame.stl and cover.stl are rigidly transformed components of "
        f"alexyu132/zcar stl/tray1.stl, revision {provenance['revision']}.\n"
        "Source: https://github.com/alexyu132/zcar ; license: GPL-3.0.\n"
        "battery.stl is a provisional geometric box generated by RaceRemote.\n",
        encoding="utf-8")
    report = {
        "source": provenance["source"], "revision": provenance["revision"],
        "source_sha256": {k: v["sha256"] for k, v in provenance["files"].items()},
        "units": provenance["units"],
        "axes": "X across chassis, Y along chassis, Z up; origin at frame bounds minimum",
        "alignment_vertex_to_assembly_surface": {"frame": frame_error, "cover": cover_error},
        "battery_mm": [49, 18, 15],
        "battery_center_mm": [24.75, 55, 10.25],
        "dimensions_status": "Seller dimensions; user batteries not measured",
        "checks": measurements,
        "limits": ["No wires, connectors, body shell or added electronics",
                   "No manufacturing tolerances, retention or physical validation",
                   "Zero overlap establishes geometry only; no distance tolerance test",
                   "Frame and cover use closed print meshes; other assembly parts use bounding boxes"],
    }
    (output / "report.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    fig, axes = plt.subplots(1, 2, figsize=(12, 5), constrained_layout=True)
    for ax, normal, origin_plane, indices, labels, title in [
        (axes[0], [0, 1, 0], [0, 55, 0], [0, 2], ["X (mm)", "Z (mm)"], "Cross-section at Y = 55 mm"),
        (axes[1], [0, 0, 1], [0, 0, 10.25], [0, 1], ["X (mm)", "Y (mm)"], "Horizontal section at Z = 10.25 mm"),
    ]:
        for name, mesh, color in [("Frame", frame, "#386cb0"), ("Cover", cover, "#666666")]:
            section = mesh.section(plane_origin=origin_plane, plane_normal=normal)
            if section is not None:
                for i, line in enumerate(section.discrete):
                    ax.plot(line[:, indices[0]], line[:, indices[1]], color=color,
                            label=name if i == 0 else None)
        low = battery.bounds[0, indices]
        size = battery.extents[indices]
        ax.add_patch(Rectangle(low, *size, color="#ef8a23", alpha=0.6, label="Battery envelope"))
        ax.autoscale_view()
        ax.set_aspect("equal")
        ax.set(xlabel=labels[0], ylabel=labels[1], title=title)
        ax.grid(alpha=0.2)
        ax.legend(loc="upper right", fontsize=8)
    fig.suptitle("zcar + LW 601844HP: provisional 49 x 18 x 15 mm envelope\n"
                 "Wires, body, retention and print tolerances excluded", fontsize=12)
    fig.savefig(output / "sections.png", dpi=160)
    plt.close(fig)
    print(json.dumps(measurements, indent=2))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("checkout", type=Path)
    parser.add_argument("--output", type=Path, default=Path("build/cad-layout"))
    args = parser.parse_args()
    main(args.checkout, args.output)
